Higher order HAL implementation, num_knots argument for speed increase, formula interface
tlverse/hal9001 pull request #77
Opened 2021-01-30 01:51 UTC by Larsvanderlaan

smoothness_degrees argument allows you to specify smoothness of hal fit in each function.
num_knots argument allows you to specify for each degree interaction how many knot points the corresponding (tensor-product) basis functions should have.
Formula_hal function for specifying formula and monotonicity constraints.

There are some tests and documentation but I still need to work a bit more on this.

2021-02-17 19:59 UTC, jeremyrcoyle approved these changes
everything passing on appveyor and locally. LGTM!

2021-02-17 22:10 UTC, nhejazi requested changes

2021-02-17 22:10 UTC, nhejazi commented on R/hal.R
> +    }
```suggestion
    if(adaptive_smoothing && all(smoothness_orders != 0)) {
      include_lower_order <- TRUE
      include_zero_order <- TRUE
    } else {
      include_zero_order <- FALSE
      include_lower_order <- FALSE
    }
```

2021-02-17 22:10 UTC, nhejazi commented on R/hal.R
> +  }
```suggestion
  if(!inherits(Y, "Surv") & prediction_bounds == "default") {
    # This would break if Y was a survival object as in coxnet
    prediction_bounds <- c(min(Y) - stats::sd(Y)/2, max(Y) + stats::sd(Y)/2)
  } else if(inherits(Y, "Surv") & prediction_bounds == "default") {
    prediction_bounds <- NULL
  }
```

2021-02-17 22:10 UTC, nhejazi commented on R/hal.R
> +    return(500/d)
Could we abstract the 50 and 500 constants to an argument? If not, it would good to describe this in the `description` tag to make it clearer.

2021-02-17 22:10 UTC, nhejazi commented on R/make_basis.R
> +basis_list_cols <- function(cols, x, smoothness_orders, include_zero_order, include_lower_order = F) {
```suggestion
basis_list_cols <- function(cols, x, smoothness_orders, include_zero_order, include_lower_order = FALSE) {
```

2021-02-17 22:10 UTC, nhejazi commented on R/make_basis.R
> +  all_basis_lists <- apply(all_cols, 2, basis_list_cols, x = x, smoothness_orders = smoothness_orders, include_zero_order = include_zero_order, include_lower_order=include_lower_order)
```suggestion
  all_basis_lists <- apply(all_cols, 2, basis_list_cols, x = x, smoothness_orders = smoothness_orders, include_zero_order = include_zero_order, include_lower_order = include_lower_order)
```

2021-02-17 22:10 UTC, nhejazi commented on R/make_basis.R
> +enumerate_basis <- function(x, max_degree = NULL, smoothness_orders = rep(0, ncol(x)), include_zero_order = F, include_lower_order = F, num_knots = NULL){
```suggestion
enumerate_basis <- function(x, max_degree = NULL, smoothness_orders = rep(0, ncol(x)), include_zero_order = FALSE, include_lower_order = FALSE, num_knots = NULL){
```

2021-02-17 22:10 UTC, nhejazi commented on R/make_basis.R
> +  if(any(smoothness_orders>0)){
```suggestion
  if (any(smoothness_orders > 0)) {
```

2021-02-17 22:10 UTC, nhejazi commented on DESCRIPTION
>  Package: hal9001
@Larsvanderlaan please add yourself as a contributor in the `DESCRIPTION` file. See below for some comments about code style (you might be able to automatically commit them via GitHub). After resolving these, please run `styler::style_pkg()` (equivalently, `make style` from the helper `Makefile`), then commit the updates changes and push. At that point, we should be good to merge. After merging to the `devel` branch, I'll regenerate the `pkgdown` site.

2021-02-18 03:14 UTC, nhejazi approved these changes
LGTM! Thanks for the quick turnaround and all the work on this @Larsvanderlaan

2021-02-18 06:19 UTC, merged